In [ ]:
import torch

create a uninitializaed tensor of size (5,3)

In [ ]:
x = torch.empty(5,3)
x

tensor([[3.5248e-30, 3.0733e-41, 1.0240e-01],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [6.2479e-32, 3.0733e-41, 5.1305e-33]])

Create a tensor of size (5,3) of random values.

In [ ]:
x = torch.rand(5, 3)
x

tensor([[0.3698, 0.0729, 0.3724],
        [0.5871, 0.6035, 0.7450],
        [0.5976, 0.1294, 0.2447],
        [0.7407, 0.0985, 0.5452],
        [0.0658, 0.1653, 0.3766]])

Create a tensor of size (5,3) of zeros, type is long.

In [ ]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

Create a tensor of size (5,3) of ones, type is double.

In [ ]:
x = torch.ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Create a tensor of size like x of random values, type is long.

In [ ]:
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[0.3335, 0.3213, 0.4877],
        [0.5933, 0.9210, 0.8022],
        [0.0842, 0.6413, 0.4098],
        [0.6142, 0.3255, 0.9849],
        [0.7713, 0.2165, 0.6584]])

Create a tensor from python list.

In [ ]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

Print the size of the tensor and tensor arithmatic.

In [ ]:
x = torch.ones(5,3)
print(x.size())

# initialize another tensor called y
y = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(y.size())
# add two tensors
result = x + y
print(result)

# Method 2
# result = torch.add(x,y)
# print(result)

# Method 3
# result = torch.empty(5, 3)
# torch.add(x, y, out=result)
# print(result)

# Method 4
# y.add_(x)
# print(y)


torch.Size([5, 3])
torch.Size([5, 3])
tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.],
        [11., 12., 13.],
        [14., 15., 16.]])


Select part of the tensor.

In [ ]:
print(y)
temp = y[:,1]
print(temp)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
tensor([ 2,  5,  8, 11, 14])


Resize

In [ ]:
x = torch.randn(4,4)
print(x)
y = x.view(16) # resize x to one dimentional tensor
print(y)
print(x.size(),y.size())

tensor([[ 0.0190,  0.1350, -0.0315,  0.6508],
        [-0.5859,  0.3460,  0.1350,  0.0881],
        [ 0.8605, -0.9134,  0.3311,  0.2386],
        [-0.6012,  1.6718, -0.2581,  0.6081]])
tensor([ 0.0190,  0.1350, -0.0315,  0.6508, -0.5859,  0.3460,  0.1350,  0.0881,
         0.8605, -0.9134,  0.3311,  0.2386, -0.6012,  1.6718, -0.2581,  0.6081])
torch.Size([4, 4]) torch.Size([16])


In [ ]:
print(x)
y = x.view(2,8) # traverse x from every row, and resize
print(y)
print(x.size(),y.size())

tensor([[ 0.0190,  0.1350, -0.0315,  0.6508],
        [-0.5859,  0.3460,  0.1350,  0.0881],
        [ 0.8605, -0.9134,  0.3311,  0.2386],
        [-0.6012,  1.6718, -0.2581,  0.6081]])
tensor([[ 0.0190,  0.1350, -0.0315,  0.6508, -0.5859,  0.3460,  0.1350,  0.0881],
        [ 0.8605, -0.9134,  0.3311,  0.2386, -0.6012,  1.6718, -0.2581,  0.6081]])
torch.Size([4, 4]) torch.Size([2, 8])


In [ ]:
print(x)
z = x.view(-1,8) # same as above but only given second dimension, the first dimention is calculated automatically
print(z)
print(x.size(),z.size)

tensor([[ 0.0190,  0.1350, -0.0315,  0.6508],
        [-0.5859,  0.3460,  0.1350,  0.0881],
        [ 0.8605, -0.9134,  0.3311,  0.2386],
        [-0.6012,  1.6718, -0.2581,  0.6081]])
tensor([[ 0.0190,  0.1350, -0.0315,  0.6508, -0.5859,  0.3460,  0.1350,  0.0881],
        [ 0.8605, -0.9134,  0.3311,  0.2386, -0.6012,  1.6718, -0.2581,  0.6081]])
torch.Size([4, 4]) <built-in method size of Tensor object at 0x7f4d8441ea70>


Extract number from tensor

In [ ]:
x = torch.randn(1)
print(x)
temp = x.item()
print(temp)

tensor([-0.8057])
-0.8057359457015991


**Numpy**

In [ ]:
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [ ]:
a.add_(1) # add the given number element-wise
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Create tensor from numpy

In [ ]:
import numpy as np

In [ ]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
np.add(a,1,out=a) # a = a + 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**Auto-Differential in tensor**

In [ ]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = x + 2
print(y)
print(y.grad_fn) # AddBackward

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [ ]:
z = y*y*3 # z = 3y^2
out = z.mean() # out = 0.25*sum(3y^2)

print(z) # MulBackward
print(out) # MeanBackWard

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


**Gradient**

In [ ]:
out.backward() # out = 0.25*sum(3y^2) = 0.25*sum(3*(x+2)^2)
print(out)

tensor(27., grad_fn=<MeanBackward0>)


Print the gradient d(out)/dx

In [ ]:
print(x.grad) # gradient = 0.5*3*(x+2) = 0.5*3*3

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


View the process of calculating gradient for a vector

In [ ]:
x = torch.randn(3,requires_grad=True)
print(x)

y = x*2 # y = 2x
print(y)
print(y.data)
print(y.data.norm()) # L2-norm

tensor([-0.2053,  0.1247,  0.7780], requires_grad=True)
tensor([-0.4106,  0.2494,  1.5560], grad_fn=<MulBackward0>)
tensor([-0.4106,  0.2494,  1.5560])
tensor(1.6285)


In [ ]:
while y.data.norm() < 1000:
  y = y*2
print(y)

tensor([-420.4053,  255.4222, 1593.3810], grad_fn=<MulBackward0>)


Calculate the gradient at position v

In [ ]:
v = torch.tensor([0.1,1,0.0001],dtype=torch.float)
y.backward(v)

result = x.grad # dy/dx at position v
print(result)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


**Networks**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Net(nn.Module):
  def __init__(self):
    